### PR TITLE
Piosenka: songs/Zbroja.xml

### PR DESCRIPTION
**Pull request by Adam-Foland**
[Link do edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-08-9766-Zbroja.xml&file=songs%2FZbroja.xml&user=Adam-Foland)

Piosenka Zbroja: Initial

Za kilka minut pojawi się tu wyrenderowana piosenka (PDF).
Ktoś też zrecenzuje/zaakceptuje Twoje zmiany. Może też mieć tutaj dodatkowe komentarze/pytania.

Możesz zawsze wrócić do [edytora](https://songbook.21wdw.org/editor?baseUrl=https%3A%2F%2Fghe.songbook.21wdw.org%2F&branch=se-2023-01-08-9766-Zbroja.xml&file=songs%2FZbroja.xml&user=Adam-Foland) by nanieść dodatkowe poprawki.

### CODE REVIEW

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Fb16d97ada522cf4873487b93f96e3ef9f701623e_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Fb16d97ada522cf4873487b93f96e3ef9f701623e_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F67919358744991f4ed4eeeaeb9918fe2798bfe37_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F67919358744991f4ed4eeeaeb9918fe2798bfe37_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Fdf06e8bc417ca17241488952a8e49b038c762702_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Fdf06e8bc417ca17241488952a8e49b038c762702_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F94cc0f9c2a4d63479a4d1abbbd96c519f9419700_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F94cc0f9c2a4d63479a4d1abbbd96c519f9419700_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F1686565077a3caad88edb06c938091ed1b9560e3_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F1686565077a3caad88edb06c938091ed1b9560e3_a5.pdf?alt=media) podano.

**Comment by ptabor** [comment]
@Adam-Foland:  Oznaczyłem akordy jako "ważne" w pierwszej zwrotce i refrenie. Spójrz czy to ma sens, proszę.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Ff7726ad8baca5ecde693dbe503985759721df105_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Ff7726ad8baca5ecde693dbe503985759721df105_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F9b3024f23466b1c9840ad8c863b9b7d54e9e1d67_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F9b3024f23466b1c9840ad8c863b9b7d54e9e1d67_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F7db8d676b99dc77419de92b9bfdf65ae85322047_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F7db8d676b99dc77419de92b9bfdf65ae85322047_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F9e8214ec3cc6cba6514de63d94fef4c4d3010c11_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F9e8214ec3cc6cba6514de63d94fef4c4d3010c11_a5.pdf?alt=media) podano.

**Comment by ptabor** [comment]
Milczenie jest znakiem zgody. Wbijam.

**Pull request merged**
