### PR TITLE
Normalizacja tytułów piosenek (nazw plików)

### PR DESCRIPTION
**Pull request by ktab15**
change name of songs and delete duplicate

### CODE REVIEW

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F753804c3ee602c99618bd8ce48c09ef111047d92_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F753804c3ee602c99618bd8ce48c09ef111047d92_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Ff0a6ec4a116e6a89d579550f78775bf2d47cd030_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Ff0a6ec4a116e6a89d579550f78775bf2d47cd030_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F21629955fe378d7d5fb51acfb55ead49de440522_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2F21629955fe378d7d5fb51acfb55ead49de440522_a5.pdf?alt=media) podano.

**Comment by wdw21-druh** [comment]
[New PDF](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Fb88b9546fd87cb9a594113127bae41aa613ebfa1_a5.pdf?alt=media) is ready, my lord (available for ~14 days).

Cieplutkiego [PDFa](https://firebasestorage.googleapis.com/v0/b/wdw-21.appspot.com/o/wdw21%2Fsongbook%2Fb88b9546fd87cb9a594113127bae41aa613ebfa1_a5.pdf?alt=media) podano.

**Review by ptabor — APPROVED** [review]

**Pull request merged**
